# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apimanager-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apimanager-example

  # Rx
  pod 'RxSwift'

  # Network
  pod 'Alamofire'
  pod 'RxAlamofire'

  # UI
  pod 'SnapKit'

end
